project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources: 
    - "assets"

website:
  title: "EVA MARIA"
  twitter-card: false
  favicon: "./assets/img/headshot_1.jpeg"
  site-url: "https://www.emcorregidor.github.io"
  open-graph: true
  navbar:
    background: white
    left:
      - text: "Research"
        href: research.html
      - text: "Teaching"
        href: teaching.html
    right:
      - icon: github
        href: https://github.com/emcorregidor
#      - icon: linkedin
#        href: PUT LINK TO LINKEDIN PAGE HERE
  page-footer:
    center: 
      - text: "© Copyright 2025"

format:
  html:
    theme:
      light: ./assets/css/theme-light.scss
      dark: [darkly, ./assets/css/theme-dark.scss]
    toc: true



